name: End-to-end user journey tests
on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [main]
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - run: corepack enable
      - run: pnpm install

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: blob-report
          path: blob-report/
          retention-days: 30
