# We've configured Renovate to open bump PRs for Remix dependencies within our
# test fixtures. This workflow sends notifications when one of these PRs fails.

name: Notify on Remix bump failures

on: status
jobs:
  notify-on-failure:
    if: github.event.state == 'error' || github.event.state == 'failure'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Check for required label
        id: check_label
        uses: actions/github-script@v6
        with:
          script: |
            const {owner, repo} = context.repo;
            const { data: pullRequests } = await github.repos.listPullRequests({
              owner,
              repo,
              state: 'open',
              head: `${owner}:${github.event.sha}`
            });
            const pullRequest = pullRequests?.[0] ?? null;
            if (pullRequest == null) {
              core.setOutput("label_exists", "false");
              return;
            }

            // See `renovate.json5` at project root.
            const requiredLabel = "bump-framework-in-fixtures";
            const labelExists = pullRequest.labels.some(label => label.name === requiredLabel);
            core.setOutput("label_exists", labelExists ? "true" : "false");
            core.setOutput("pr_url", pullRequest.url);

      - name: Create issue on failure
        if: ${{ steps.check_label.outputs.label_exists == 'true' }}
        uses: actions/github-script@v6
        with:
          script: |
            const ISSUE_LABEL = "framework-bump-failure";
            const issues = await github.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: "open",
              labels: ISSUE_LABEL
            });
            if (issues.length > 0) {
              console.log(`Open issue already exists: ${issues[0].html_url}`);
              return;
            }
            const issue = await github.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: "Possible regression with new framework release",
              labels: ISSUE_LABEL,
              body: `A framework release bump in test fixtures has failed. Check ${steps.check_label.outputs.pr_url}.`
            });

            console.log(`Created issue: ${issue.data.html_url}`);
